# Generated by Django 5.0.2 on 2024-04-13 19:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='login',
            fields=[
                ('log_id', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=100, verbose_name='username')),
                ('password', models.CharField(max_length=100, verbose_name='password')),
                ('role', models.CharField(max_length=100, verbose_name='role')),
            ],
        ),
        migrations.CreateModel(
            name='medicine',
            fields=[
                ('med_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
                ('description', models.CharField(max_length=300, verbose_name='Description')),
                ('composition', models.CharField(max_length=300, verbose_name='Composition')),
                ('pharmaceutical_form', models.CharField(max_length=300, verbose_name='Pharmaceutical Form')),
                ('age', models.CharField(max_length=100, verbose_name='Age')),
                ('method_of_administration', models.CharField(max_length=300, verbose_name='Method of Administration')),
                ('contraindications', models.CharField(max_length=500, verbose_name='Contraindications')),
                ('precautions', models.CharField(max_length=500, verbose_name='Precautions')),
            ],
        ),
        migrations.CreateModel(
            name='Hospital',
            fields=[
                ('hospital_id', models.AutoField(primary_key=True, serialize=False)),
                ('hospital_name', models.CharField(max_length=100, verbose_name='Hospital Name')),
                ('license', models.CharField(max_length=100, verbose_name='license Status from Wholesaler')),
                ('status', models.CharField(max_length=100, verbose_name='status')),
                ('hospital_address', models.CharField(max_length=200, verbose_name='hospital_address')),
                ('hospital_phone', models.CharField(max_length=100, verbose_name='hospital_phone')),
                ('login', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='hospital', to='vaccine.login')),
            ],
        ),
        migrations.CreateModel(
            name='distributor',
            fields=[
                ('distributor_id', models.AutoField(primary_key=True, serialize=False)),
                ('distributor_name', models.CharField(max_length=100, verbose_name='Company/Distributor Name')),
                ('address', models.CharField(max_length=100, verbose_name='address')),
                ('license_no', models.CharField(max_length=100, verbose_name='license_no')),
                ('phone', models.CharField(max_length=12, verbose_name='phone')),
                ('status', models.CharField(max_length=10, verbose_name='status')),
                ('login', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='vaccine.login')),
            ],
        ),
        migrations.CreateModel(
            name='manufactuer',
            fields=[
                ('manufactuer_id', models.AutoField(primary_key=True, serialize=False)),
                ('company_name', models.CharField(max_length=100, verbose_name='company name')),
                ('address', models.CharField(max_length=100, verbose_name='address')),
                ('licence_no', models.CharField(max_length=100, verbose_name='licence no')),
                ('phone_no', models.CharField(max_length=100, verbose_name='phone no')),
                ('status', models.CharField(max_length=100, verbose_name='status')),
                ('login', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='manufacturers', to='vaccine.login')),
            ],
        ),
        migrations.CreateModel(
            name='DistributorAuthorizationRequest',
            fields=[
                ('request_id', models.AutoField(primary_key=True, serialize=False)),
                ('company_name', models.CharField(max_length=100, verbose_name='Company/Wholesaler Name')),
                ('documents', models.FileField(upload_to='authorization_documents/', verbose_name='Documents')),
                ('status', models.CharField(max_length=100, verbose_name='Status')),
                ('distributor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vaccine.distributor')),
                ('Hospital', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='vaccine.hospital')),
                ('manufactuer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='vaccine.manufactuer')),
            ],
        ),
        migrations.CreateModel(
            name='Phrama',
            fields=[
                ('PhramaStaff_id', models.AutoField(primary_key=True, serialize=False)),
                ('PhramaStaff_name', models.CharField(max_length=100, verbose_name='Name')),
                ('PhramaStaff_gender', models.CharField(max_length=100, verbose_name='Staff_gender')),
                ('PhramaStaff_address', models.CharField(max_length=500, verbose_name='Staff_address')),
                ('PhramaStaff_email', models.EmailField(max_length=200, verbose_name='Staff_email')),
                ('PhramaStaff_phone', models.CharField(max_length=100, verbose_name='Staff_phone')),
                ('PhramaStaff_qualification', models.CharField(max_length=200, verbose_name='Staff_qualification')),
                ('PhramaStaff_designation', models.CharField(max_length=100, verbose_name='Staff_designation')),
                ('PhramaStaff_photo', models.FileField(max_length=1000, upload_to='images/', verbose_name='Staff_photo')),
                ('PhramaStaff_status', models.CharField(default='', max_length=50, verbose_name='Staff_status')),
                ('Staff_logid', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='vaccine.login')),
            ],
        ),
        migrations.CreateModel(
            name='vaccinerequest',
            fields=[
                ('vaccine_id', models.AutoField(primary_key=True, serialize=False)),
                ('vaccine_name', models.CharField(max_length=100)),
                ('date', models.DateField()),
                ('required_documents', models.FileField(upload_to='manufacture_documents/')),
                ('additional_details', models.TextField()),
                ('stock', models.CharField(max_length=100)),
                ('status', models.CharField(max_length=100, verbose_name='status')),
                ('manufactuer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vaccine.manufactuer')),
                ('medicine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vaccine.medicine')),
            ],
        ),
        migrations.CreateModel(
            name='BookedVaccineRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('phone_number', models.CharField(max_length=15)),
                ('stock', models.CharField(max_length=100)),
                ('additional_details', models.TextField()),
                ('status', models.CharField(default='booked', max_length=100)),
                ('hospital', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vaccine.hospital')),
                ('vaccinerequest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vaccine.vaccinerequest')),
            ],
        ),
        migrations.CreateModel(
            name='booked',
            fields=[
                ('booked_id', models.AutoField(primary_key=True, serialize=False)),
                ('Hospital', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='vaccine.hospital')),
                ('vaccinerequest', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='vaccine.vaccinerequest')),
            ],
        ),
    ]
