# Generated by Django 5.0.2 on 2024-04-14 07:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vaccine', '0002_bookedvaccinerequest_distributor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookedvaccinerequest',
            name='distributor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='vaccine.distributor'),
        ),
    ]
