# Generated by Django 5.0.2 on 2024-04-14 08:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vaccine', '0003_alter_bookedvaccinerequest_distributor'),
    ]

    operations = [
        migrations.CreateModel(
            name='expiry',
            fields=[
                ('exp_id', models.AutoField(primary_key=True, serialize=False)),
                ('mfg_date', models.DateField()),
                ('exp_date', models.DateField()),
                ('manufactuer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='vaccine.manufactuer')),
                ('vaccinerequest', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='vaccine.vaccinerequest')),
            ],
        ),
    ]
